# Generated by Django 5.1.3 on 2024-12-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('sal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('comm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('hire_date', models.DateField()),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('mgr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
